apiVersion: v1
kind: Service
metadata:
  name: payment-db
  namespace: foodrush
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: payment-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: payment-db
  namespace: foodrush
spec:
  serviceName: payment-db
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: payment-db
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: payment_db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: foodrush-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: foodrush-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: payment-db-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d payment_db"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\" -d payment_db"]
            initialDelaySeconds: 20
            periodSeconds: 15
  volumeClaimTemplates:
    - metadata:
        name: payment-db-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
