apiVersion: v1
kind: Secret
metadata:
  name: foodrush-secret
  namespace: foodrush
type: Opaque
stringData:
  JWT_SECRET: foodrush-super-secret
  POSTGRES_USER: foodrush
  POSTGRES_PASSWORD: foodrush123
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: admin
